//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reports()
        {
            this.Logs = new HashSet<Logs>();
        }
    
        public int Id { get; set; }
        public string Date { get; set; }
        public string Place { get; set; }
        public string Comments { get; set; }
        public Nullable<int> InformantsID { get; set; }
        public Nullable<int> AgentsID { get; set; }
        public Nullable<int> ObservantsID { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual Informants Informants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logs> Logs { get; set; }
        public virtual Observants Observants { get; set; }
    }
}
